Adapt `ps_specials` for multiples versions of PrestaShop
PrestaShop/ps_specials pull request #10
Opened 2022-07-07 07:02 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Adapt `ps_specials` for multiples versions of PrestaShop
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Relative to PrestaShop/Prestashop#28988
| How to test?  | Try this module in version `< 1.7.4.0` and in recent version (`8.0.0`)

2022-07-07 09:20 UTC, kpodemski requested changes
Maybe we could simply change the minimum required PS version? There are no other significant updates for this module

2022-07-08 07:12 UTC, Progi1984 commented
@kpodemski I have done changes for being compatible with old versions. We can change the minimum required PS version when it will be really useful.

2022-07-19 10:23 UTC, kpodemski approved these changes

2022-08-12 17:07 UTC, khouloudbelguith reviewed
Hello @Progi1984,

I tried this PR with those versions

- 178x + PHP 7.2 => OK
- 8.0.x + php8.1 => ok
- PS1712 + php7.1 => NOK, after installing the PR, I have an exception in the FO
![image](https://user-images.githubusercontent.com/16067358/184408121-13a8fe1a-26ad-4082-94c9-4c7e6d2bb54a.png)
- PS1725 + PHP 7.1 => NOK after installing the PR, I have an exception in the FO
![image](https://user-images.githubusercontent.com/16067358/184408181-c97b9094-cae2-4de7-8ed4-ce25fffcfbf9.png)
- PS1744 + php7.0 => NOK, after installing the PR, I have an exception in the module manager configure page & in the FO 
I attached a screen record

https://user-images.githubusercontent.com/16067358/184408455-fd5fe8c7-5641-4251-8de0-16b022dfeb8a.mp4

Thanks!

2022-08-30 14:34 UTC, zuk3975 approved these changes

2022-09-04 14:00 UTC, leemyongpakvn reviewed
I guess L229 must be
if (version_compare(`_PS_VERSION_`, '1.7.4', '>=')) {

2022-09-22 19:52 UTC, matks approved these changes

2022-09-23 01:55 UTC, leemyongpakvn commented
@matks I think there is a mistake at [Line 229](https://github.com/PrestaShop/ps_specials/pull/10/files/b0b5934bd9c351d0a13db03a5556ce68f9922202#diff-d5f68d478680ed7436708049fda08f577aef7ca9b5c5cd9284debb4b03125035R229) because we have no **PHP_VERSION** 1.7.4

2022-09-23 07:50 UTC, kpodemski submitted a review, later dismissed

2022-09-23 07:50 UTC, kpodemski commented on ps_specials.php
> +        if (version_compare(PHP_VERSION, '1.7.4', '>=')) {
```suggestion
        if (version_compare(_PS_VERSION_, '1.7.4', '>=')) {
```

2022-09-23 07:50 UTC, kpodemski commented
@leemyongpakvn you're right! thanks

2023-01-12 13:40 UTC, Hlavtox approved these changes

2023-01-12 14:14 UTC, kpodemski approved these changes

2023-01-16 13:45 UTC, florine2623 reviewed
Hello @Progi1984 ,

Tested with the following PS versions and PHP 7.1 and 7.4 :
- PS 1.7.3.2 ✅ 
- PS 1.7.5.2 ✅ 
- PS 1.7.8.8 ✅ 
- PS 8.0.1 ✅ 
- PS develop ✅ 
- PS 1.7.4.0 ❌ Exception in FO :
<img width="1035" alt="Screenshot 2023-01-16 at 11 33 41" src="https://user-images.githubusercontent.com/16019289/212690108-77b3800b-8e8e-4428-9315-7f7e9e0f0653.png">

Could you check for the latest version ?
I have the same issue as @khouloudbelguith .

Thanks!

2023-01-16 13:51 UTC, Hlavtox commented on ps_specials.php
> +        if (version_compare(_PS_VERSION_, '1.7.4', '>=')) {
```suggestion
        if (version_compare(_PS_VERSION_, '1.7.5', '>=')) {
```

1.7.4 is still using the old path, change the condition and it should work ;-)

2023-01-17 13:41 UTC, Hlavtox commented
@Progi1984 Commited to the branch, hope you don't mind. So we can get this out of the way and release it. :-)
The file was moved on 1.7.5 higher - see https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/src/Core/Product/ProductListingPresenter.php

2023-01-17 14:54 UTC, florine2623 approved these changes
Hello @Hlavtox ,

The module works well on version before 1.7.4.0 and in recent versions !

PS 1.7.3.2 ✅
PS 1.7.4.0 ✅ 
PS 1.7.5.2 ✅
PS 1.7.8.8 ✅
PS 8.0.1 ✅
PS develop ✅


Thanks !!

2023-01-17 14:55 UTC, merged