Allow only integers for the configuration 'Number of elements to display'
PrestaShop/ps_specials pull request #8
Opened 2022-06-15 09:54 UTC by AlexTechDev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Allow only integers for the configuration 'Number of elements to display'
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#28663
| How to test?  | See PrestaShop/Prestashop#28663

2022-06-18 14:35 UTC, okom3pom commented
Hello @AlexTechDev you have to run cs-fixer on your file.

2022-07-04 13:27 UTC, MeKeyCool commented
@AlexTechDev you can find a example of command to run : https://github.com/PrestaShop/ps_specials/runs/6897334061?check_suite_focus=true#step:6:1

2022-09-23 07:51 UTC, kpodemski commented
@AlexTechDev ping

2022-09-27 06:27 UTC, kpodemski commented
@AlexTechDev cs-fixer is still not happy, remember that you can use it locally on your computer

2022-09-27 08:16 UTC, AlexTechDev commented
Thanks for the support @kpodemski 
I have some problem with cs-fixer on my computer and I use one validator online but as you say it doesn't work.
I will fix cs-fixer on my computer and upload again

2023-01-17 15:30 UTC, SharakPL requested changes
These should fix CS

2023-01-17 15:30 UTC, SharakPL commented on ps_specials.php
> +                Configuration::updateValue('BLOCKSPECIALS_SPECIALS_NBR', (int)Tools::getValue('BLOCKSPECIALS_SPECIALS_NBR'));
```suggestion
                Configuration::updateValue('BLOCKSPECIALS_SPECIALS_NBR', (int) Tools::getValue('BLOCKSPECIALS_SPECIALS_NBR'));
```

2023-01-17 15:30 UTC, SharakPL commented on ps_specials.php
> +                $output .= $this->displayConfirmation($this->trans('The settings have been updated.', array(), 'Admin.Notifications.Success'));
```suggestion
                $output .= $this->displayConfirmation($this->trans('The settings have been updated.', [], 'Admin.Notifications.Success'));
```

2023-01-17 15:30 UTC, SharakPL commented on ps_specials.php
> +        return $output.$this->renderForm();
```suggestion
        return $output . $this->renderForm();
```

2023-01-17 15:49 UTC, Hlavtox commented
@AlexTechDev Fixed the CS, hope you don't mind. 🙏

2023-01-17 15:53 UTC, SharakPL approved these changes

2023-01-18 09:54 UTC, djoelleuch approved these changes
Hello @AlexTechDev ,

Tested with the following PS versions and PHP 7.4 :
 - PS 8.0.1 :heavy_check_mark: 
 - PS 1.7.8.8 :heavy_check_mark: 
 - PS 8.0.0 :heavy_check_mark: 
 
![PR2](https://user-images.githubusercontent.com/115152460/213140054-60e65b6d-2999-4095-a6d9-3ae6c3d57485.png)

It's QA approved  ! 

Thank you for your PR :rocket:

2023-01-18 09:59 UTC, merged

2023-01-18 09:59 UTC, Hlavtox commented
Thanks @AlexTechDev & @djoelleuch! :-)